#!/usr/bin/env python3
"""Emit the valid warptiling configs as a data table for autotune.cu.

Only data comes out of here: a constexpr array and an index list. The
benchmark driver is hand-written in autotune.cu and never generated.

Why generate at all: nvbench's type axes take a Cartesian product, and for
eight parameters ~75% of it is invalid. Invalid configs don't merely skip at
runtime -- a zero PACK_A is a division by zero inside the kernel body, which
fails to compile. So the constraints are enumerated here and only survivors
reach the compiler.

Usage:  python3 gen_autotune.py [size] > autotune_cfgs.inc
"""
import itertools
import sys

SIZE = int(sys.argv[1]) if len(sys.argv) > 1 else 4096
WARPSIZE = 32

# Default space: 196 valid of 256. Widen for a deeper search -- the full grid
# BM/BN(64,128,256) BK(8,16,32) WM/WN(16,32,64,128) WNITER(1,2,4) yields 1370
# valid configs and roughly 90 minutes of nvbench time.
AXES = dict(
    BM=(64, 128),
    BN=(64, 128),
    BK=(8, 16),
    TM=(4, 8),
    TN=(4, 8),
    WM=(32, 64),
    WN=(32, 64),
    WI=(1, 2),
)


def valid(BM, BN, BK, TM, TN, WM, WN, WI):
    """Every constraint 08_warptiling.cu actually relies on."""
    # warp tile decomposes into sub-tiles, covered by exactly 32 threads
    denom = WARPSIZE * TM * TN * WI
    if (WM * WN) % denom:
        return False
    MWITER = (WM * WN) // denom
    if MWITER < 1 or WM % MWITER or WN % WI:
        return False
    NSUB, MSUB = WN // WI, WM // MWITER
    if NSUB % TN or MSUB % TM:
        return False
    if (NSUB // TN) * (MSUB // TM) != WARPSIZE:
        return False

    # warps tile the block
    if BM % WM or BN % WN:
        return False
    nthreads = (BM // WM) * (BN // WN) * WARPSIZE
    if not (WARPSIZE <= nthreads <= 1024):
        return False

    # float4 alignment on both global->shared hops, and in the epilogue
    if BK % 4 or BN % 4 or TN % 4:
        return False
    if nthreads % (BK // 4) or nthreads % (BN // 4):
        return False

    # the staging loops must tile exactly: stride must equal the rows one
    # pass covers, or rows get skipped or double-written
    if (BM * BK // 4) % nthreads or (BK * BN // 4) % nthreads:
        return False
    PACK_A = BM * BK // 4 // nthreads
    PACK_B = BK * BN // 4 // nthreads
    if PACK_A < 1 or PACK_B < 1 or BM % PACK_A or BK % PACK_B:
        return False
    if BM // PACK_A != nthreads // (BK // 4):
        return False
    if BK // PACK_B != nthreads // (BN // 4):
        return False

    # resource ceilings (hard wall is 255 registers/thread)
    if MWITER * TM * WI * TN > 128:
        return False
    if (BM * BK + BK * BN) * 4 > 48 * 1024:
        return False

    # the kernel has no bounds checks
    return not (SIZE % BM or SIZE % BN or SIZE % BK)


keys = list(AXES)
cfgs = [p for p in itertools.product(*AXES.values()) if valid(*p)]
total = 1
for v in AXES.values():
    total *= len(v)
sys.stderr.write(f"{len(cfgs)} valid of {total} ({100.0*len(cfgs)/total:.0f}%)\n")

print(f"// GENERATED by gen_autotune.py {SIZE} -- data only, do not edit.")
print(f"// {len(cfgs)} valid configs of {total} combinations.")
print("constexpr Cfg CFGS[] = {")
for BM, BN, BK, TM, TN, WM, WN, WI in cfgs:
    print(f"    {{{BM:4},{BN:4},{BK:3},{TM:2},{TN:2},{WM:4},{WN:4},{WI:2}}},")
print("};")
print(f"#define CFG_COUNT {len(cfgs)}")
print("#define CFG_INDICES " + ", ".join(str(i) for i in range(len(cfgs))))
